---
- name: restart machine 
  command: shutdown -r now 
  async: 0
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  #local_action: wait_for host={{ ip }} port=22 delay=15 state=started
  #local_action: wait_for host={{ inventory_hostname }} port=22 state=started timeout=15
  #local_action: wait_for host={{ inventory_hostname }} port=22 state=started
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=15
  sudo: false

