VAGRANTFILE_API_VERSION = "2"
BOX_TIMEOUT = 180

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ARTACK/debian-jessie"
  config.vm.boot_timeout = BOX_TIMEOUT
  config.vm.box_url = "https://atlas.hashicorp.com/ARTACK/boxes/debian-jessie"
  config.vm.network :public_network
  
  # disable USB 2.0
  config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
  end
  
   config.vm.provision :ansible do |ansible|
     ansible.playbook = "../ansible/aws-dns.yml"
     ansible.inventory_path = "../ansible/ansible_hosts"
     ansible.limit = 'all'
     ansible.verbose = "-vvvv"
   end #end config.vm.provision


end #end Vagrant
